/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fees_report_management_system;

import java.sql.*;
import java.awt.Color;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.ObjectInputStream;

/**
 *
 * @author HP
 */
public class PrintReciept extends javax.swing.JFrame {

    /**
     * Creates new form PrintReciept
     */
    public PrintReciept() {
        initComponents();
        getRecords();
        Container C =  getContentPane();
        C.setBackground(new Color(153,0,153));
    }
    
    
    public void getRecords(){
        try {
            Connection con1 = ConnectionProvider.getConnection();
            String Query = "select * from fees_details order by reciept_no desc limit 1";
            PreparedStatement pstmt = con1.prepareStatement(Query);
            ResultSet rs = pstmt.executeQuery();
            rs.next();
            
            txt_Reciept_No.setText(rs.getString("reciept_no"));
            txt_Payment_Mode.setText(rs.getString("payment_mode"));
            
            String PM = rs.getString("payment_mode");
            
            if(PM.equals("Cash")){
                lbl_cheque_dd.setText("");
                txt_Cheque_DD.setText("");
                lbl_BankName.setText("");
                txt_Bank_Name.setText("");  
            }
            
            if(PM.equals("DD")){
                lbl_cheque_dd.setText("DD No. : ");
                txt_Cheque_DD.setText(rs.getString("dd_no"));
                txt_Bank_Name.setText(rs.getString("bank_name"));  
            }
            
            if(PM.equals("Cheque")){
                lbl_cheque_dd.setText("Cheque No. : ");
                txt_Cheque_DD.setText(rs.getString("cheque_no"));
                txt_Bank_Name.setText(rs.getString("bank_name"));  
            }
            
            if(PM.equals("Card")){
                lbl_cheque_dd.setText("-");
                txt_Cheque_DD.setText(rs.getString("-"));
                txt_Bank_Name.setText(rs.getString("bank_name"));  
            }
            
            txt_Recieved_From.setText(rs.getString("student_name"));
            txt_YearFrom.setText(rs.getString("year1"));
            txt_YearTo.setText(rs.getString("year2"));
            txt_Date.setText(rs.getString("date"));
            txt_GSTIN.setText(rs.getString("gstin"));
            lbl_CourseName.setText(rs.getString("course_name"));
            txt_Amount.setText(rs.getString("amount"));
            txt_CGST.setText(rs.getString("cgst"));
            txt_SGST.setText(rs.getString("sgst"));
            txt_TotalAmount.setText(rs.getString("total_amount"));
            txt_TotalInWords.setText(rs.getString("total_in_words"));
            txt_Remark.setText(rs.getString("remark"));
            
            
            
            
            
            
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelSideBar = new javax.swing.JPanel();
        PanelSearchRecord = new javax.swing.JPanel();
        btnSearchRecord = new javax.swing.JLabel();
        PanelEditCourses = new javax.swing.JPanel();
        btnEditCourses = new javax.swing.JLabel();
        PanelCourseList = new javax.swing.JPanel();
        btnCourseList = new javax.swing.JLabel();
        PanelViewAllRecords = new javax.swing.JPanel();
        btnViewAllRecords = new javax.swing.JLabel();
        PanelBack = new javax.swing.JPanel();
        btnBack = new javax.swing.JLabel();
        PanelHome = new javax.swing.JPanel();
        btnHome = new javax.swing.JLabel();
        PanelLogout = new javax.swing.JPanel();
        btnLogout = new javax.swing.JLabel();
        PanelPrint = new javax.swing.JPanel();
        btnPrint = new javax.swing.JLabel();
        PanelEdit = new javax.swing.JPanel();
        btnEdit = new javax.swing.JLabel();
        PanelPrint_Main = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_Reciept_No = new javax.swing.JLabel();
        lbl_cheque_dd = new javax.swing.JLabel();
        lbl_Cheque = new javax.swing.JLabel();
        lbl_BankName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_Payment_Mode = new javax.swing.JLabel();
        txt_Cheque_DD = new javax.swing.JLabel();
        txt_Bank_Name = new javax.swing.JLabel();
        lbl_BankName1 = new javax.swing.JLabel();
        lbl_BankName2 = new javax.swing.JLabel();
        txt_YearFrom = new javax.swing.JLabel();
        txt_YearFrom1 = new javax.swing.JLabel();
        txt_YearTo = new javax.swing.JLabel();
        txt_Recieved_From = new javax.swing.JLabel();
        lbl_BankName3 = new javax.swing.JLabel();
        txt_Date = new javax.swing.JLabel();
        lbl_BankName5 = new javax.swing.JLabel();
        txt_GSTIN = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_SrNo = new javax.swing.JLabel();
        lbl_Course = new javax.swing.JLabel();
        lbl_Amount = new javax.swing.JLabel();
        lbl_CGST = new javax.swing.JLabel();
        lbl_SGST = new javax.swing.JLabel();
        txt_TotalInWords = new javax.swing.JLabel();
        lbl_CourseName = new javax.swing.JLabel();
        txt_CGST = new javax.swing.JLabel();
        txt_SGST = new javax.swing.JLabel();
        txt_Amount = new javax.swing.JLabel();
        txt_TotalAmount = new javax.swing.JLabel();
        lbl_SrNo1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lbl_SGST2 = new javax.swing.JLabel();
        lbl_SGST3 = new javax.swing.JLabel();
        lbl_SGST4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Remark = new javax.swing.JTextArea();
        lbl_SGST5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelSideBar.setBackground(new java.awt.Color(102, 0, 102));
        PanelSideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelSearchRecord.setBackground(new java.awt.Color(102, 0, 102));
        PanelSearchRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelSearchRecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearchRecord.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        btnSearchRecord.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_report_management_system/Images/search2.png"))); // NOI18N
        btnSearchRecord.setText(" Search Record");
        btnSearchRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchRecordMouseExited(evt);
            }
        });
        PanelSearchRecord.add(btnSearchRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 60));

        PanelSideBar.add(PanelSearchRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 240, 80));

        PanelEditCourses.setBackground(new java.awt.Color(102, 0, 102));
        PanelEditCourses.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelEditCourses.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditCourses.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        btnEditCourses.setForeground(new java.awt.Color(255, 255, 255));
        btnEditCourses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_report_management_system/Images/edit2.png"))); // NOI18N
        btnEditCourses.setText("   Edit Courses");
        btnEditCourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditCoursesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditCoursesMouseExited(evt);
            }
        });
        PanelEditCourses.add(btnEditCourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 200, 60));

        PanelSideBar.add(PanelEditCourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 240, 80));

        PanelCourseList.setBackground(new java.awt.Color(102, 0, 102));
        PanelCourseList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelCourseList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCourseList.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        btnCourseList.setForeground(new java.awt.Color(255, 255, 255));
        btnCourseList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_report_management_system/Images/list.png"))); // NOI18N
        btnCourseList.setText(" Course List");
        btnCourseList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCourseListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCourseListMouseExited(evt);
            }
        });
        PanelCourseList.add(btnCourseList, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 200, 60));

        PanelSideBar.add(PanelCourseList, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 240, 80));

        PanelViewAllRecords.setBackground(new java.awt.Color(102, 0, 102));
        PanelViewAllRecords.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelViewAllRecords.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewAllRecords.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        btnViewAllRecords.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAllRecords.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_report_management_system/Images/view all record.png"))); // NOI18N
        btnViewAllRecords.setText(" View All Records");
        btnViewAllRecords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewAllRecordsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewAllRecordsMouseExited(evt);
            }
        });
        PanelViewAllRecords.add(btnViewAllRecords, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 60));

        PanelSideBar.add(PanelViewAllRecords, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 240, 80));

        PanelBack.setBackground(new java.awt.Color(102, 0, 102));
        PanelBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_report_management_system/Images/back-button.png"))); // NOI18N
        btnBack.setText("       Back ");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        PanelBack.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 190, 60));

        PanelSideBar.add(PanelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 240, 80));

        PanelHome.setBackground(new java.awt.Color(102, 0, 102));
        PanelHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_report_management_system/Images/home.png"))); // NOI18N
        btnHome.setText("  HOME");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });
        PanelHome.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 200, 60));

        PanelSideBar.add(PanelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 240, 80));

        PanelLogout.setBackground(new java.awt.Color(102, 0, 102));
        PanelLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogout.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_report_management_system/Images/logout.png"))); // NOI18N
        btnLogout.setText("      Logout");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        PanelLogout.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 200, 60));

        PanelSideBar.add(PanelLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 240, 80));

        PanelPrint.setBackground(new java.awt.Color(102, 0, 102));
        PanelPrint.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelPrint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrint.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_report_management_system/Images/printer-.png"))); // NOI18N
        btnPrint.setText("       Print");
        btnPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrintMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrintMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrintMouseExited(evt);
            }
        });
        PanelPrint.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 200, 60));

        PanelSideBar.add(PanelPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, 240, 80));

        PanelEdit.setBackground(new java.awt.Color(102, 0, 102));
        PanelEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelEdit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEdit.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_report_management_system/Images/edit2.png"))); // NOI18N
        btnEdit.setText("       Edit");
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditMouseExited(evt);
            }
        });
        PanelEdit.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 200, 60));

        PanelSideBar.add(PanelEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 730, 240, 80));

        getContentPane().add(PanelSideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 840));

        PanelPrint_Main.setBackground(new java.awt.Color(255, 255, 255));
        PanelPrint_Main.setPreferredSize(new java.awt.Dimension(600, 470));
        PanelPrint_Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 102));
        jLabel11.setText("Avengers");
        PanelPrint_Main.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 140, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 102));
        jLabel9.setText("Iron Man and Team");
        PanelPrint_Main.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 250, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 102));
        jLabel10.setText("Avengers Office, Stark Tower, 890 Fifth Avenue, Manhattan, New York City");
        PanelPrint_Main.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 480, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_report_management_system/Images/clg_avengers.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        PanelPrint_Main.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 210, 90));

        txt_Reciept_No.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_Reciept_No.setForeground(new java.awt.Color(102, 0, 102));
        txt_Reciept_No.setText("Reciept No. :  ABC-");
        PanelPrint_Main.add(txt_Reciept_No, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 130, -1));

        lbl_cheque_dd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_cheque_dd.setForeground(new java.awt.Color(102, 0, 102));
        lbl_cheque_dd.setText("Mode of Payment :");
        PanelPrint_Main.add(lbl_cheque_dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 130, -1));

        lbl_Cheque.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Cheque.setForeground(new java.awt.Color(102, 0, 102));
        lbl_Cheque.setText("Cheque/DD No :");
        PanelPrint_Main.add(lbl_Cheque, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 110, -1));

        lbl_BankName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_BankName.setForeground(new java.awt.Color(102, 0, 102));
        lbl_BankName.setText("Bank Name :");
        PanelPrint_Main.add(lbl_BankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 90, -1));

        jPanel2.setBackground(new java.awt.Color(153, 0, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        PanelPrint_Main.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 940, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("Reciept No. :  ABC-");
        PanelPrint_Main.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 130, -1));

        txt_Payment_Mode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_Payment_Mode.setForeground(new java.awt.Color(102, 0, 102));
        txt_Payment_Mode.setText("Payment Mode");
        PanelPrint_Main.add(txt_Payment_Mode, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 130, -1));

        txt_Cheque_DD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_Cheque_DD.setForeground(new java.awt.Color(102, 0, 102));
        txt_Cheque_DD.setText("Cheque/DD");
        PanelPrint_Main.add(txt_Cheque_DD, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 130, -1));

        txt_Bank_Name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_Bank_Name.setForeground(new java.awt.Color(102, 0, 102));
        txt_Bank_Name.setText("BankName");
        PanelPrint_Main.add(txt_Bank_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 130, -1));

        lbl_BankName1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_BankName1.setForeground(new java.awt.Color(102, 0, 102));
        lbl_BankName1.setText("Recieved From :");
        PanelPrint_Main.add(lbl_BankName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 110, -1));

        lbl_BankName2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_BankName2.setForeground(new java.awt.Color(102, 0, 102));
        lbl_BankName2.setText("The following payment in the college office for year");
        PanelPrint_Main.add(lbl_BankName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 340, -1));

        txt_YearFrom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_YearFrom.setText("From");
        PanelPrint_Main.add(txt_YearFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 60, -1));

        txt_YearFrom1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_YearFrom1.setText("-");
        PanelPrint_Main.add(txt_YearFrom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 10, -1));

        txt_YearTo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_YearTo.setText("To");
        PanelPrint_Main.add(txt_YearTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 60, -1));

        txt_Recieved_From.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_Recieved_From.setForeground(new java.awt.Color(102, 0, 102));
        txt_Recieved_From.setText("Recieved From");
        PanelPrint_Main.add(txt_Recieved_From, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 110, -1));

        lbl_BankName3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_BankName3.setForeground(new java.awt.Color(102, 0, 102));
        lbl_BankName3.setText("Date :");
        PanelPrint_Main.add(lbl_BankName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 50, -1));

        txt_Date.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_Date.setForeground(new java.awt.Color(102, 0, 102));
        txt_Date.setText("Date");
        PanelPrint_Main.add(txt_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, 140, -1));

        lbl_BankName5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_BankName5.setForeground(new java.awt.Color(102, 0, 102));
        lbl_BankName5.setText("GSTIN No :");
        PanelPrint_Main.add(lbl_BankName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 80, -1));

        txt_GSTIN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_GSTIN.setForeground(new java.awt.Color(102, 0, 102));
        txt_GSTIN.setText("GST No");
        PanelPrint_Main.add(txt_GSTIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, 170, -1));

        jSeparator1.setBackground(new java.awt.Color(102, 0, 102));
        jSeparator1.setForeground(new java.awt.Color(102, 0, 102));
        PanelPrint_Main.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 660, 280, 10));

        jSeparator2.setBackground(new java.awt.Color(102, 0, 102));
        jSeparator2.setForeground(new java.awt.Color(102, 0, 102));
        PanelPrint_Main.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 910, 10));

        lbl_SrNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_SrNo.setForeground(new java.awt.Color(102, 0, 102));
        lbl_SrNo.setText("Sr. No.");
        PanelPrint_Main.add(lbl_SrNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 70, -1));

        lbl_Course.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Course.setForeground(new java.awt.Color(102, 0, 102));
        lbl_Course.setText("Course");
        PanelPrint_Main.add(lbl_Course, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 80, -1));

        lbl_Amount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Amount.setForeground(new java.awt.Color(102, 0, 102));
        lbl_Amount.setText("Amount (Rs)");
        PanelPrint_Main.add(lbl_Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, 80, -1));

        lbl_CGST.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_CGST.setForeground(new java.awt.Color(102, 0, 102));
        lbl_CGST.setText("CGST");
        PanelPrint_Main.add(lbl_CGST, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 80, -1));

        lbl_SGST.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_SGST.setForeground(new java.awt.Color(102, 0, 102));
        lbl_SGST.setText("SGST");
        PanelPrint_Main.add(lbl_SGST, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 80, -1));

        txt_TotalInWords.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_TotalInWords.setForeground(new java.awt.Color(102, 0, 102));
        txt_TotalInWords.setText("Total in Words");
        PanelPrint_Main.add(txt_TotalInWords, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, 430, -1));

        lbl_CourseName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_CourseName.setForeground(new java.awt.Color(102, 0, 102));
        lbl_CourseName.setText("CourseName");
        PanelPrint_Main.add(lbl_CourseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 210, -1));

        txt_CGST.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_CGST.setForeground(new java.awt.Color(102, 0, 102));
        txt_CGST.setText("CGST Amount");
        PanelPrint_Main.add(txt_CGST, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, 110, -1));

        txt_SGST.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_SGST.setForeground(new java.awt.Color(102, 0, 102));
        txt_SGST.setText("SGST Amount");
        PanelPrint_Main.add(txt_SGST, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, 110, 20));

        txt_Amount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_Amount.setForeground(new java.awt.Color(102, 0, 102));
        txt_Amount.setText("Amount");
        PanelPrint_Main.add(txt_Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, 140, -1));

        txt_TotalAmount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_TotalAmount.setForeground(new java.awt.Color(102, 0, 102));
        txt_TotalAmount.setText("Final Course Amount");
        PanelPrint_Main.add(txt_TotalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, 150, -1));

        lbl_SrNo1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_SrNo1.setForeground(new java.awt.Color(102, 0, 102));
        lbl_SrNo1.setText("1");
        PanelPrint_Main.add(lbl_SrNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 30, -1));

        jSeparator3.setBackground(new java.awt.Color(102, 0, 102));
        jSeparator3.setForeground(new java.awt.Color(102, 0, 102));
        PanelPrint_Main.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 910, 10));

        lbl_SGST2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_SGST2.setForeground(new java.awt.Color(102, 0, 102));
        lbl_SGST2.setText("Final Amount");
        PanelPrint_Main.add(lbl_SGST2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 510, 110, -1));

        lbl_SGST3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_SGST3.setForeground(new java.awt.Color(102, 0, 102));
        lbl_SGST3.setText("Remark :");
        PanelPrint_Main.add(lbl_SGST3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 70, -1));

        lbl_SGST4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_SGST4.setForeground(new java.awt.Color(102, 0, 102));
        lbl_SGST4.setText("Recievers Signature & Stamp");
        PanelPrint_Main.add(lbl_SGST4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 670, 200, -1));

        txt_Remark.setColumns(20);
        txt_Remark.setRows(5);
        jScrollPane1.setViewportView(txt_Remark);

        PanelPrint_Main.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 610, 300, 60));

        lbl_SGST5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_SGST5.setForeground(new java.awt.Color(102, 0, 102));
        lbl_SGST5.setText("Total in Words :");
        PanelPrint_Main.add(lbl_SGST5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 110, -1));

        jSeparator4.setBackground(new java.awt.Color(102, 0, 102));
        jSeparator4.setForeground(new java.awt.Color(102, 0, 102));
        PanelPrint_Main.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, 350, 10));

        getContentPane().add(PanelPrint_Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 940, 780));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 0, 50, 930));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Sitka Small", 1, 36)); // NOI18N
        jLabel2.setText("PRINT RECIEPT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 310, 60));

        setSize(new java.awt.Dimension(1314, 844));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchRecordMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(153,0,153);
        PanelSearchRecord.setBackground(clr);

    }//GEN-LAST:event_btnSearchRecordMouseEntered

    private void btnSearchRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchRecordMouseExited
        // TODO add your handling code here:
        Color clr = new Color(102,0,102);
        PanelSearchRecord.setBackground(clr);
    }//GEN-LAST:event_btnSearchRecordMouseExited

    private void btnEditCoursesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCoursesMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(153,0,153);
        PanelEditCourses.setBackground(clr);
    }//GEN-LAST:event_btnEditCoursesMouseEntered

    private void btnEditCoursesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCoursesMouseExited
        // TODO add your handling code here:
        Color clr = new Color(102,0,102);
        PanelEditCourses.setBackground(clr);
    }//GEN-LAST:event_btnEditCoursesMouseExited

    private void btnCourseListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseListMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(153,0,153);
        PanelCourseList.setBackground(clr);
    }//GEN-LAST:event_btnCourseListMouseEntered

    private void btnCourseListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseListMouseExited
        // TODO add your handling code here:
        Color clr = new Color(102,0,102);
        PanelCourseList.setBackground(clr);
    }//GEN-LAST:event_btnCourseListMouseExited

    private void btnViewAllRecordsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllRecordsMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(153,0,153);
        PanelViewAllRecords.setBackground(clr);
    }//GEN-LAST:event_btnViewAllRecordsMouseEntered

    private void btnViewAllRecordsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllRecordsMouseExited
        // TODO add your handling code here:
        Color clr = new Color(102,0,102);
        PanelViewAllRecords.setBackground(clr);
    }//GEN-LAST:event_btnViewAllRecordsMouseExited

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(153,0,153);
        PanelBack.setBackground(clr);
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        // TODO add your handling code here:
        Color clr = new Color(102,0,102);
        PanelBack.setBackground(clr);
    }//GEN-LAST:event_btnBackMouseExited

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(153,0,153);
        PanelHome.setBackground(clr);
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        // TODO add your handling code here:
        Color clr = new Color(102,0,102);
        PanelHome.setBackground(clr);
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(153,0,153);
        PanelLogout.setBackground(clr);
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        // TODO add your handling code here:
        Color clr = new Color(102,0,102);
        PanelLogout.setBackground(clr);
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(153,0,153);
        PanelEdit.setBackground(clr);
    }//GEN-LAST:event_btnEditMouseEntered

    private void btnEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseExited
        // TODO add your handling code here:
        Color clr = new Color(102,0,102);
        PanelEdit.setBackground(clr);
    }//GEN-LAST:event_btnEditMouseExited

    private void btnPrintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(153,0,153);
        PanelPrint.setBackground(clr);
 

    }//GEN-LAST:event_btnPrintMouseEntered

    private void btnPrintMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseExited
        // TODO add your handling code here:
        Color clr = new Color(102,0,102);
        PanelPrint.setBackground(clr);
    }//GEN-LAST:event_btnPrintMouseExited

    private void btnPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseClicked
        // TODO add your handling code here:
         PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);
                
                PanelPrint_Main.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
}
        }
    }//GEN-LAST:event_btnPrintMouseClicked

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        // TODO add your handling code here:
        UpdateFeesDetails update = new UpdateFeesDetails();
        update.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEditMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintReciept().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBack;
    private javax.swing.JPanel PanelCourseList;
    private javax.swing.JPanel PanelEdit;
    private javax.swing.JPanel PanelEditCourses;
    private javax.swing.JPanel PanelHome;
    private javax.swing.JPanel PanelLogout;
    private javax.swing.JPanel PanelPrint;
    private javax.swing.JPanel PanelPrint_Main;
    private javax.swing.JPanel PanelSearchRecord;
    private javax.swing.JPanel PanelSideBar;
    private javax.swing.JPanel PanelViewAllRecords;
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnCourseList;
    private javax.swing.JLabel btnEdit;
    private javax.swing.JLabel btnEditCourses;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnPrint;
    private javax.swing.JLabel btnSearchRecord;
    private javax.swing.JLabel btnViewAllRecords;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbl_Amount;
    private javax.swing.JLabel lbl_BankName;
    private javax.swing.JLabel lbl_BankName1;
    private javax.swing.JLabel lbl_BankName2;
    private javax.swing.JLabel lbl_BankName3;
    private javax.swing.JLabel lbl_BankName5;
    private javax.swing.JLabel lbl_CGST;
    private javax.swing.JLabel lbl_Cheque;
    private javax.swing.JLabel lbl_Course;
    private javax.swing.JLabel lbl_CourseName;
    private javax.swing.JLabel lbl_SGST;
    private javax.swing.JLabel lbl_SGST2;
    private javax.swing.JLabel lbl_SGST3;
    private javax.swing.JLabel lbl_SGST4;
    private javax.swing.JLabel lbl_SGST5;
    private javax.swing.JLabel lbl_SrNo;
    private javax.swing.JLabel lbl_SrNo1;
    private javax.swing.JLabel lbl_cheque_dd;
    private javax.swing.JLabel txt_Amount;
    private javax.swing.JLabel txt_Bank_Name;
    private javax.swing.JLabel txt_CGST;
    private javax.swing.JLabel txt_Cheque_DD;
    private javax.swing.JLabel txt_Date;
    private javax.swing.JLabel txt_GSTIN;
    private javax.swing.JLabel txt_Payment_Mode;
    private javax.swing.JLabel txt_Reciept_No;
    private javax.swing.JLabel txt_Recieved_From;
    private javax.swing.JTextArea txt_Remark;
    private javax.swing.JLabel txt_SGST;
    private javax.swing.JLabel txt_TotalAmount;
    private javax.swing.JLabel txt_TotalInWords;
    private javax.swing.JLabel txt_YearFrom;
    private javax.swing.JLabel txt_YearFrom1;
    private javax.swing.JLabel txt_YearTo;
    // End of variables declaration//GEN-END:variables
}
